### ISSUE TITLE
Atmel studio fail to connect?

### ISSUE THREAD

**Issue by dingdinglhz** [ElTangas/STK2UPDI#2]
![updi](https://user-images.githubusercontent.com/3640674/35827048-aa6bcdb8-0a88-11e8-9b2e-681fec219eda.PNG)

I tried to upload the code and connect to Atmel studio but I got this error here. 
Any hints?
Thanks for developing this tools!

**Comment by ElTangas** [comment]
Have you disabled the auto-reset feature of Arduino with a capacitor?

**Comment by dingdinglhz** [comment]
Yes I did.

**Comment by ElTangas** [comment]
Your Arduino has a mega168 or a mega328?
I don't know if this is your issue, but anyway, I'll update the makefile so that it's easier to edit and select a mega168 or a mega328p target.
